country: br
root: br.hp.php9.cc
frontend_languages: en_US pt_BR
backend_languages: en_US
frontend_themes: HPOLS/default
localizations: br-pt
server_ips: 172.31.62.55 172.31.49.41 172.31.54.71
varnish_ip: 172.31.62.55
primary_server_ip: 172.31.54.71
server_names: hpbra hpbrb hpbrx
server_region: saopaulo
database:
  backup_server_name: hpbrx
  backup_dir: /home/ubuntu/db/BR
  db_host: hpolslatampro-ar-br.cyfhmojdkg3e.sa-east-1.rds.amazonaws.com
  db_user: hpreadonly
  db_password: IkFjsMzM5WJ2OuEUiqbsQg==
  db_name: hpbr
  ignore_tables: reporting_system_updates hpols_order_api_history
  related_countries: ar br
  mysql_client_version: 8
aws:
  aws_bin: /usr/local/bin/aws
  s3_bucket: br.media.hptiendaenlinea.com
  s3_file_bucket: br.files.hptiendaenlinea.com
  s3_bigtable_bucket: large-tables
  s3_endpoint:
  cloudfront_distribution_id: EMM236E2H3JY7
source_root: /home/ubuntu/release_sources
html_root: /usr/share/nginx/html
release_dir: /usr/share/nginx/html/releases_br
maintenance_file: maintenance.html
sitemap_dirs:
sitemap_files: sitemap.xml
composer_bin: /usr/bin/composer
scp_bin: scp
ssh_bin: ssh
cms_url: https://www.hp.com/br-pt/shop/
category_url: https://www.hp.com/br-pt/shop/impressoras.html
product_url: https://www.hp.com/br-pt/shop/impressoras/impressora-multifuncional-hp-deskjet-ink-advantage-3776-j9v88a.html
